### ISSUE TITLE
[Question] Linux?

### ISSUE THREAD

**Issue by choman** [alunux/usbip-gui-utils#1]
Does this work on linux (specifically centos 7.5)?

do you have compile instructions?

Also, I see it's still under development. but how functional is it?

**Comment by vleeuwenmenno** [comment]
I have tried to compile on Ubuntu 20.04 with no success.
```
error: taking address of packed member of ‘struct op_devlist_reply’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  171 |         usbip_net_pack_uint32_t(pack, &(reply)->ndev);                                             \
      |                                       ^~~~~~~~~~~~~~
````
I getting a lot of compilation errors as these ^^
